Explicitely reference Move Microsoft.Bcl.AsyncInterfaces
In order to avoid having the clients to explicitely
referece Microsoft.Bcl.AsyncInterfaces, let the Amazon.QLDB.Driver
do it for them

If this is not made, then the clients will the get the following error

```
Severity Code Description Project File Line Suppression State
Error CS0012 The type 'IAsyncEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```
and they will have to reference the package by themselves to fix this